### ISSUE TITLE
Multiple domains enhancement

### ISSUE THREAD

**Issue by dzogrim** [Behemouth/WeedProxite#2]
Greetings @Behemouth,

Will you consider add a feature to WeedProxite that can handle multiple domains like:

``` HTML
http://www.themirroredwebsite.com
http://static.themirroredwebsite.com
http://api.themirroredwebsite.com
http://video.themirroredwebsite.com
```

because at this time, it is not working. Or I missed something in the conf. files… ?
Thanks !

**Comment by Behemouth** [comment]
All available configurations are in `Config.coffee` : https://github.com/Behemouth/WeedProxite/blob/master/lib/Config.coffee#L38

This situation you can use `allowHosts` option.

**Comment by dzogrim** [comment]
Yeap… thanks @Behemouth I've seen that and added sub-domains, but actually even using this option, seems not enough to load _every_ called static files… :/ 
The browser _never_ stop to load… but do not load files. When aborded, finally starts to load files directly on the original website… not from mirror. 
I suspect content in CSS like 

``` CSS
<span data-img-size-big="http://static…
```

not beeing rewrited.
I tried to add some to https://github.com/Behemouth/WeedProxite/blob/master/lib/rewrite.coffee#L84 without effects.

**Comment by Behemouth** [comment]
Try to simply add this line in your site's own `main.html` before `client.run()` （Example: https://github.com/Behemouth/WeedProxite/blob/master/lib/tpl/main.html#L121）:

```
client.rewriter.rule({attr:'data-img-size-big',rewrite:function (src) {
    return WeedProxite.rewrite.url(src,client.config);
})
```

**Comment by dzogrim** [comment]
Thanks a lot !!
WeedProxite rocks.
