### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by dzogrim** [Behemouth/WeedProxite#4]
Hi!
I reinstalled WeedProxite and encoutered an error : files are _missing_ from Git and of course when `proxite init` too :

```
./lib/tpl/static/bundle.js
./lib/tpl/static/bundle.min.js
```

As confirmed here : https://github.com/Behemouth/WeedProxite/tree/master/lib/tpl/static
Could u please check? Thx

**Comment by Behemouth** [comment]
Sorry for the troubles. It was fixed now. Please update to the latest version.

**Comment by Behemouth** [comment]
Not fixed on Windows.

**Comment by dzogrim** [comment]
Hi!
Thanks for your answer.

**Comment by Behemouth** [comment]
Fixed in the latest 0.0.7 version.
