### ISSUE TITLE
NGinX proxy/cache config

### ISSUE THREAD

**Issue by dzogrim** [Behemouth/WeedProxite#5]
Hi!
Did you try to put NGinX in front of WeedProxite?
It's working, but someone randomly generating a tons of HTTP 400 errors after the spinning wheel of WeedProxite and with infinite-never-stop browser loading wheel:

```
400 Bad Request
Invalid Proxy API Action: raw; URL: /-proxite-/raw/undefined
```

Log only showing:
`"GET /-proxite-/raw/undefined HTTP/1.1" 400 103 "http://mirror.blahblah.tld/journal/international" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0"`

What does `/-proxite-/raw/undefined` correspond for?
Usually, `/-proxite-/` works ; examples:

```
[14/Aug/2015:16:36:50 +0200] "GET /-proxite-/static/spinner.gif HTTP/1.1" 304 0 "http://mirror.blahblah.tld/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0"
[14/Aug/2015:16:36:50 +0200] "GET /-proxite-/manifest.appcache?version=d8363379de1ca8447e024efffdbc192e HTTP/1.1" 200 153 "http://mirror.blahblah.tld/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0"
```

since I added in the NGinX configuration:

```
    location ^/-proxite-/ {
        alias /var/www/reverse/;
    }
```

But surely missed something here…
HTTP 400 errors eventually dissmissed when I empty browser's Cache and offline web content and data.

**Comment by Behemouth** [comment]
See the updated README.

**Comment by dzogrim** [comment]
Yeap. Thanks… I'm sorry but it is still the same after some clicks:
`400 Bad Request
Invalid Proxy API Action: raw; URL: /-proxite-/raw/undefined`
even with the simple nginx configuration you suggest.
I tried on a brand-new VPS with a public website I can have hand on… _front_ and _back_.
This is the exactly the same _[…]_
I really don't know what I missed… :( Thanks for your help.

**Comment by Behemouth** [comment]
Update WeedProxite and Clear your browser cache.

**Comment by Behemouth** [comment]
Sorry I forgot to tell you to remove `your-site/static` directory, in the new version it doesn't need this directory.
